#!/bin/bash

page_cnt="$(sysctl -n vm.pages)"
free_cnt="$(sysctl -n vm.page_free_count)"
used=$(((page_cnt - free_cnt) * 4096 / 1024 / 1024))
# total=$((page_cnt * 4096 / 1024 / 1024))
echo "$used MB"
